export const LOGIN_STATUS = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
};

export const LOGOUT_STATUS = {
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'LOGOUT_FAIL',
};

export const STATE = {
  PENDING: 'PENDING',
  RESOLVE: 'RESOLVE',
  READY: 'READY',
  REJECT: 'REJECT',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  NEED_ACCEPT: 'NEED_ACCEPT',
  ERROR: 'ERROR',
  CHANGE_KEY_MENU: 'CHANGE_KEY_MENU',
  CHANGE_SUB_KEY_MENU: 'CHANGE_SUB_KEY_MENU',
  ACCESS_CHAT: 'ACCESS_CHAT',
  EDIT_USER: 'EDIT_USER',
  EDIT_GROUP: 'EDIT_GROUP',
  OLD_FRIEND: 'OLD_FRIEND',
};

export const SOCKET = {
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  CONNECTED_SUCCESS: 'CONNECTED_SUCCESS',
  CONNECTED_FAIL: 'CONNECTED_FAIL',
  DISCONNECTED_SUCCESS: 'DISCONNECTED_SUCCESS',
  DISCONNECTED_FAIL: 'DISCONNECTED_FAIL',
};
