export const CHAT_STATUS = {
    SELECTED_CHAT: 'SELECTED_CHAT',
}

export const NOTIFICATIONS = {
    FRIENDS: 'FRIENDS',
    GROUPS: 'GROUPS',
    MESSAGES: 'MESSAGES',
    CHAT: 'CHAT',
    NOTIFICATION: 'NOTIFICATION',
    NOTIFICATION_FRIENDS: 'NOTIFICATION_FRIENDS',
    NOTIFICATION_GROUPS: 'NOTIFICATION_GROUPS',
    NOTIFICATION_MESSAGES: 'NOTIFICATION_MESSAGES',
    NOTIFICATION_CHAT: 'NOTIFICATION_CHAT',
    NOTIFICATION_NOTIFICATION: 'NOTIFICATION_NOTIFICATION',
    NOTIFICATION_FRIENDS_COUNT: 'NOTIFICATION_FRIENDS_COUNT',
    NOTIFICATION_GROUPS_COUNT: 'NOTIFICATION_GROUPS_COUNT',
    NOTIFICATION_MESSAGES_COUNT: 'NOTIFICATION_MESSAGES_COUNT',
    NOTIFICATION_CHAT_COUNT: 'NOTIFICATION_CHAT_COUNT',
    NOTIFICATION_NOTIFICATION_COUNT: 'NOTIFICATION_NOTIFICATION_COUNT',
}