export const LOGIN_STATUS = {
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
}

export const LOGOUT_STATUS = {
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',
}

export const STATE = {
    PENDING: 'PENDING',
    RESOLVE: true,
    REJECT: false,
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
}