export const CHAT_STATUS = {
    SELECTED_CHAT: 'SELECTED_CHAT',
    PRIVATE_CHAT: 'PRIVATE_CHAT',
    GROUP_CHAT: 'GROUP_CHAT',
    FETCH: 'FETCH',
}

export const NOTIFICATIONS = {
    FRIENDS: 'FRIENDS',
    GROUPS: 'GROUPS',
    MESSAGES: 'MESSAGES',
    CHAT: 'CHAT',
    FETCH_NOTIFICATIONS_FUNC: 'FETCH_NOTIFICATIONS',
    NOTIFICATION: 'NOTIFICATION',
    NOTIFICATION_FRIENDS: 'NOTIFICATION_FRIENDS',
    NOTIFICATION_GROUPS: 'NOTIFICATION_GROUPS',
    NOTIFICATION_MESSAGES: 'NOTIFICATION_MESSAGES',
    NOTIFICATION_CHAT: 'NOTIFICATION_CHAT',
    NOTIFICATION_NOTIFICATION: 'NOTIFICATION_NOTIFICATION',
    NOTIFICATION_FRIENDS_COUNT: 'NOTIFICATION_FRIENDS_COUNT',
    NOTIFICATION_GROUPS_COUNT: 'NOTIFICATION_GROUPS_COUNT',
    NOTIFICATION_MESSAGES_COUNT: 'NOTIFICATION_MESSAGES_COUNT',
    NOTIFICATION_CHAT_COUNT: 'NOTIFICATION_CHAT_COUNT',
    NOTIFICATION_NOTIFICATION_COUNT: 'NOTIFICATION_NOTIFICATION_COUNT',
}

export const MESSAGES = {
    SEND_MESSAGE_FUNC: 'SEND_MESSAGE_FUNC',
    IMAGES: 'IMAGES',
    VIDEO: 'VIDEO',
    AUDIO: 'AUDIO',
    TEXT: 'TEXT',
    STICKER: 'STICKER',
    FILE_FOLDER: 'FILE_FOLDER',

}

export const FILE_TYPE = {
    FILE: 'FILE',
    FOLDER: 'FOLDER',
    PDF: 'PDF',
    WORD: 'WORD',
    EXCEL: 'EXCEL',
    JAR: 'JAR',
}

export const METHOD_MESSAGE = {
    DELETE_MYSEFL: 'DELETE_MYSEFL',
    DELETE_ALL: 'DELETE_ALL',
    COPY: 'COPY',
    PIN: 'PIN',
    VIEW_DETAIL: 'VIEW_DETAIL',

}

export const CALL = {
    ADD_MEMBER: 'ADD_MEMBER',
    REMOVE_MEMBER: 'REMOVE_MEMBER',
    CALL_MEMBER: 'CALL_MEMBER',
    END_CALL: 'END_CALL',
    CALLING: 'CALLING',
    CALL_MEMBER_STATUS: 'CALL_MEMBER_STATUS',
    CALL_MEMBER_STATUS_END: 'CALL_MEMBER_STATUS_END',
    CALL_MEMBER_STATUS_BUSY: 'CALL_MEMBER_STATUS_BUSY',
    CALL_MEMBER_STATUS_ACCEPT: 'CALL_MEMBER_STATUS_ACCEPT',
    CALL_MEMBER_STATUS_REJECT: 'CALL_MEMBER_STATUS_REJECT',
    CALL_MEMBER_STATUS_CANCEL: 'CALL_MEMBER_STATUS_CANCEL',
    CALL_MEMBER_STATUS_LEAVE: 'CALL_MEMBER_STATUS_LEAVE',
    CALL_MEMBER_STATUS_JOIN: 'CALL_MEMBER_STATUS_JOIN',
    CALL_MEMBER_STATUS_MUTE: 'CALL_MEMBER_STATUS_MUTE',
    CALL_MEMBER_STATUS_UNMUTE: 'CALL_MEMBER_STATUS_UNMUTE',
    CALL_MEMBER_STATUS_VIDEO: 'CALL_MEMBER_STATUS_VIDEO',
    CALL_MEMBER_STATUS_AUDIO: 'CALL_MEMBER_STATUS_AUDIO',
    CALL_MEMBER_STATUS_SCREEN: 'CALL_MEMBER_STATUS_SCREEN',
    CALL_MEMBER_STATUS_SHARE: 'CALL_MEMBER_STATUS_SHARE',
}