export const CHAT_STATUS = {
  SELECTED_CHAT: 'SELECTED_CHAT',
  PRIVATE_CHAT: 'PRIVATE_CHAT',
  GROUP_CHAT: 'GROUP_CHAT',
  FETCH: 'FETCH',
};

export const NOTIFICATIONS = {
  FRIENDS: 'FRIENDS',
  GROUPS: 'GROUPS',
  MESSAGES: 'MESSAGES',
  CHAT: 'CHAT',
  FETCH_NOTIFICATIONS_FRIENDS_FUNC: 'FETCH_NOTIFICATIONS_FRIENDS_FUNC',
  FETCH_NOTIFICATIONS_CHAT_FUNC: 'FETCH_NOTIFICATIONS_CHAT_FUNC',
};

export const MESSAGES = {
  SEND_MESSAGE_FUNC: 'SEND_MESSAGE_FUNC',
  IMAGES: 'IMAGES',
  VIDEO: 'VIDEO',
  AUDIO: 'AUDIO',
  TEXT: 'TEXT',
  STICKER: 'STICKER',
  FILE_FOLDER: 'FILE_FOLDER',
  NOTIFY: 'NOTIFY',
  NEW_FRIEND: 'NEW_FRIEND',
  FETCH_MESSAGES_FUNC: 'FETCH_MESSAGES_FUNC',
};

export const FILE_TYPE = {
  FILE: 'FILE',
  FOLDER: 'FOLDER',
  PDF: 'PDF',
  WORD: 'WORD',
  EXCEL: 'EXCEL',
  JAR: 'JAR',
};

export const METHOD_MESSAGE = {
  DELETE_MYSEFL: 'DELETE_MYSEFL',
  DELETE_ALL: 'DELETE_ALL',
  COPY: 'COPY',
  PIN: 'PIN',
  VIEW_DETAIL: 'VIEW_DETAIL',
};

export const CALL = {
  ADD_MEMBER: 'ADD_MEMBER',
  REMOVE_MEMBER: 'REMOVE_MEMBER',
  CALL_MEMBER: 'CALL_MEMBER',
  END_CALL: 'END_CALL',
  CALLING: 'CALLING',
  CALL_MEMBER_STATUS: 'CALL_MEMBER_STATUS',
  CALL_MEMBER_STATUS_END: 'CALL_MEMBER_STATUS_END',
  CALL_MEMBER_STATUS_BUSY: 'CALL_MEMBER_STATUS_BUSY',
  CALL_MEMBER_STATUS_ACCEPT: 'CALL_MEMBER_STATUS_ACCEPT',
  CALL_MEMBER_STATUS_REJECT: 'CALL_MEMBER_STATUS_REJECT',
  CALL_MEMBER_STATUS_CANCEL: 'CALL_MEMBER_STATUS_CANCEL',
  CALL_MEMBER_STATUS_LEAVE: 'CALL_MEMBER_STATUS_LEAVE',
  CALL_MEMBER_STATUS_JOIN: 'CALL_MEMBER_STATUS_JOIN',
  CALL_MEMBER_STATUS_MUTE: 'CALL_MEMBER_STATUS_MUTE',
  CALL_MEMBER_STATUS_UNMUTE: 'CALL_MEMBER_STATUS_UNMUTE',
  CALL_MEMBER_STATUS_VIDEO: 'CALL_MEMBER_STATUS_VIDEO',
  CALL_MEMBER_STATUS_AUDIO: 'CALL_MEMBER_STATUS_AUDIO',
  CALL_MEMBER_STATUS_SCREEN: 'CALL_MEMBER_STATUS_SCREEN',
  CALL_MEMBER_STATUS_SHARE: 'CALL_MEMBER_STATUS_SHARE',
};

export const FILTER = {
  ALL: 'ALL',
  EMPTY: '',
  NOT_READ: 'NOT_READ',
  READ: 'READ',
  PIN: 'PIN',
  DELETE: 'DELETE',
  UNDELETE: 'UNDELETE',
  UNPIN: 'UNPIN',
  UNREAD: 'UNREAD',
  UNREAD_ALL: 'UNREAD_ALL',
  READ_ALL: 'READ_ALL',
  DELETE_ALL: 'DELETE_ALL',
  UNDELETE_ALL: 'UNDELETE_ALL',
  PIN_ALL: 'PIN_ALL',
  UNPIN_ALL: 'UNPIN_ALL',
  FRIENDS: 'FRIENDS',
};

export const SETTING = {
  SHOW_DATE: 'SHOW_DATE',
  SHOW_STATUS_ONLINE: 'SHOW_STATUS_ONLINE',
  SHOW_SEEN: 'SHOW_SEEN',
  SHOW_ALLOW_SEND_MESSAGE: 'SHOW_ALLOW_SEND_MESSAGE',
  SHOW_ALLOW_CALL: 'SHOW_ALLOW_CALL',
  ADD_FRIEND_QR: 'ADD_FRIEND_QR',
  ADD_FRIEND_GROUP: 'ADD_FRIEND_GROUP',
  ADD_FRIEND_CARD: 'ADD_FRIEND_CARD',
};
